[package]
name = "saffi"
version = "0.1.0"
edition = "2024"

[dependencies]
salloc = { path = "../salloc" }
tokio = { version = "^1", features = ["rt", "sync", "time", "macros"] }

parking_lot = "^0.12"
